version: '3.7'

services:
  my-app:
    container_name: pw-node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/.vite'
    ports:
      - '3000:3000'